python /global/homes/j/jiuy97/bin/verve/gbr-optuna.py -o Ef_rel \
--Y concat_norm_formation_rel.tsv \
-i \
ICOHP_rel_per_metal \
ICOHP_rel_per_bond \
ICOBI_rel_per_metal \
ICOBI_rel_per_bond \
MadelungL_rel \
GrossPopulationL_rel \
bond_rel \
volume_rel \
chg_rel \
mag_rel \
atomic_number \
group_id \
mass \
atomic_volume \
ionenergies1 \
ionenergies2 \
ionenergies12 \
ionenergies3 \
dipole_polarizability \
en_pauling \
density \
covalent_radius \
metallic_radius \
vdw_radius \
melting_point \
boiling_point \
evaporation_heat \
fusion_heat \
sublimation_heat \
heat_of_formation \
--X \
concat_ICOHP_rel.tsv \
concat_norm_ICOHP_rel.tsv \
concat_ICOBI_rel.tsv \
concat_norm_ICOBI_rel.tsv \
concat_norm_MadelungL_rel.tsv \
concat_GrossPopulationL_rel.tsv \
concat_bond_rel.tsv \
concat_norm_volume_rel.tsv \
concat_chg_rel.tsv \
concat_mag_rel.tsv \
concat_atomic_number.tsv \
concat_group_id.tsv \
concat_mass.tsv \
concat_atomic_volume.tsv \
concat_ionenergies_1.tsv \
concat_ionenergies_2.tsv \
concat_ionenergies_12.tsv \
concat_ionenergies_3.tsv \
concat_dipole_polarizability.tsv \
concat_en_pauling.tsv \
concat_density.tsv \
concat_covalent_radius.tsv \
concat_metallic_radius.tsv \
concat_vdw_radius.tsv \
concat_melting_point.tsv \
concat_boiling_point.tsv \
concat_evaporation_heat.tsv \
concat_fusion_heat.tsv \
concat_sublimation_heat.tsv \
concat_heat_of_formation.tsv