python ~/bin/verve/lr.py -o Ef \
--Y concat_norm_formation.tsv \
-i \
ICOHP_per_metal \
ICOHP_per_bond \
ICOBI_per_metal \
ICOBI_per_bond \
MadelungL \
GrossPopulationL \
bond \
volume \
chg \
mag \
atomic_number \
group_id \
mass \
atomic_volume \
ionenergies1 \
ionenergies2 \
ionenergies12 \
ionenergies3 \
dipole_polarizability \
en_pauling \
density \
covalent_radius \
metallic_radius \
vdw_radius \
melting_point \
boiling_point \
evaporation_heat \
fusion_heat \
sublimation_heat \
heat_of_formation \
--X \
concat_ICOHP.tsv \
concat_norm_ICOHP.tsv \
concat_ICOBI.tsv \
concat_norm_ICOBI.tsv \
concat_norm_MadelungL.tsv \
concat_GrossPopulationL.tsv \
concat_bond.tsv \
concat_norm_volume.tsv \
concat_chg.tsv \
concat_mag.tsv \
concat_atomic_number.tsv \
concat_group_id.tsv \
concat_mass.tsv \
concat_atomic_volume.tsv \
concat_ionenergies_1.tsv \
concat_ionenergies_2.tsv \
concat_ionenergies_12.tsv \
concat_ionenergies_3.tsv \
concat_dipole_polarizability.tsv \
concat_en_pauling.tsv \
concat_density.tsv \
concat_covalent_radius.tsv \
concat_metallic_radius.tsv \
concat_vdw_radius.tsv \
concat_melting_point.tsv \
concat_boiling_point.tsv \
concat_evaporation_heat.tsv \
concat_fusion_heat.tsv \
concat_sublimation_heat.tsv \
concat_heat_of_formation.tsv